### PR TITLE
Support "required" validator in oneof fields

### LINKED ISSUE #30: oneof: adding a "required" validation
Am I missing a trick, or is there currently no way to enforce that a oneof field *must* have one of the contained types? Currently the generated validator falls through to return a nil error if none of the union type members are present.

### PR DESCRIPTION
**Pull request by scele**
Fixes #30

### CODE REVIEW

**Comment by scele** [comment]
@mwitkow Would you have time to take a look at this and #44 ?

**Comment by F21** [comment]
friendly ping @mwitkow

**Comment by mwitkow** [comment]
Sorry I went a-wall. My job rarely takes me to github nowadays.
Nice, can you please rebase so the conflicting files get updated?

**Comment by fho** [comment]
merged into our fork: https://github.com/simplesurance/go-proto-validators

**Comment by Helcaraxan** [comment]
Hello @scele. Picking up this repo / PR. I have just merged your branch with `master` in #68 and it should land shortly. Closing this PR in favour of that one.

Thank you very much again for your contribution and my apologies for the long overdue activity on this PR.

**Pull request closed without merging**
